#pragma once

#define MAYJOR_NUMBER 510

#define DEVICE_NAME "Injector"

#define MAX_SYMBOL_NAME 256

enum RETURN_CODE{
    SUCCESS,
    INVALID_PARAMETER,
    INVALID_PID,
    SIGSTOP_FAILED,
    GET_USER_PAGE_REMOTE_FAILED,
    REMOTE_MEMORY_ALLOC_FAILED,
    GET_DYNAMIC_SECTION_FAILED,
};